# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  herawebapi:
    image: herawebapi
    build:
      context: .
      dockerfile: Hera.WebAPI/Dockerfile
    environment:
      - ConnectionStrings__PostgresSqlConnection="Server=localhost;Port=5432;User ID=postgres;Password=123456;Database=Hera;Integrated Security=true;Pooling=true;"
    volumes:
      - ~\.aspnet\https:C:\https:ro
    ports:
      - "5000:5000"
    depends_on:
      - "postgresdb"
  postgresdb:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "Hera"

